### ISSUE TITLE
Backspace is handled before send_text

### ISSUE THREAD

**Issue by tamo** [ueno/ibus-fep#14]
Maybe this is libfep's problem but...
1. Enable ibus-skk
2. Input something (e.g. a = "あ")
3. Convert something (e.g. Ai+SPC = "▼愛")
4. Press Backspace

gtk-immodule's result:
output 3, and then handle backspace, so the last char of 3 is deleted.
(result: "あ")

ibus-fep's result:
handle backspace, and then output 3, so the last char of 2 is deleted.
(result: "愛")

**Comment by ueno** [comment]
Thanks for the report.  Hmm, probably we should make the key event handling asynchronous.
Here is a quick fix: ueno/libskk@67894c6bdae9c9324da96f8b6b2ce51e14fce417

**Comment by tamo** [comment]
Well, ueno/libfep@67894c6 doesn't fix it. I rebuilt both libfep and ibus-fep.

**Comment by ueno** [comment]
Sorry, I actually tested it only with skkfep and it seemed to work.  I'll check the difference between ibus-fep an skkfep.

**Comment by ueno** [comment]
OK, should be fixed with ueno/libfep@28b200c111f79b2da61a269af12aeea939320fff and ueno/ibus-fep@2d52cd4cabcefc98c9cc008f6f3869b9a621de7a.

**Comment by tamo** [comment]
Thanks, it's fixed!
