### ISSUE TITLE
Arrow-keys on vim don't work

### ISSUE THREAD

**Issue by tamo** [ueno/ibus-fep#16]
cf. ueno/libfep#4

You can't use arrow-keys on "ibus-fep -- vim"
no matter what the ibus status is. ([あ] or [　])

No problem with "fep vim", so I guess it's a bug in ibus-fep.

**Comment by ueno** [comment]
I guess this is a regression of recent changes related to #14.

**Comment by ueno** [comment]
Sorry for late response.  Probably it will be fixed with the latest libfep and ibus-fep git master.

**Comment by tamo** [comment]
Confirmed it's fixed. Thanks!

BTW, the latest libfep and ibus-fep don't allow me to
disable ibus (Ctrl+SPC to change status [あ]->[  ]) with ibus-1.4.
I'll file a detailed report if you haven't noticed.

**Comment by ueno** [comment]
Hmm, can't reproduce it here (under Debian sid).  Please file a new report.  Thanks.

**Comment by tamo** [comment]
Oops, please forget it.
Now there is no problem.
I was doing something wrong, maybe adding -x to ibus-daemon options.
