### ISSUE TITLE
Client tries to execute "--" when an option or more is given

### ISSUE THREAD

**Issue by tamo** [ueno/ibus-fep#17]
Although "ibus-fep -- w3m" executes w3m,
"ibus-fep -- w3m -v" doesn't execute "w3m -v" but tries to execute "--"

```
Failed to execute child process "--" (No such file or directory)
```

**Comment by ueno** [comment]
Thanks, should be fixed with 61bbf3a8195fffec01177b15bd9e1dc91d698f69.
