### ISSUE TITLE
Auxiliary text is shown by GTK+

### ISSUE THREAD

**Issue by tamo** [ueno/ibus-fep#4]
Converting a kana string which has many candidates,
ibus-fep shows the lookup-table at the bottom line. That's OK.
But it shows the auxiliary text (ibus-skk's annotations or ibus-anthy's "(1/26)" etc.) 
as a floating GTK+ window. That's annoying.
Especially annoying when I'm inputting a text near the bottom line,
because the auxiliary text is shown over the lookup-table line.

Versions: ibus-1.4.0 + ibus-fep-1.4.3 + (ibus-skk-1.4.0 or ibus-anthy-1.2.6)

**Comment by tamo** [comment]
Interestingly, after seeing the error message of issue #5, auxiliary text is NOT displayed anymore.
Of course, you can reproduce it again if you restart ibus-daemon and ibus-fep.

**Comment by tamo** [comment]
It seems that this issue is in ibus-1.4.0.
Cannot reproduce with ibus-1.4.1.

**Comment by tamo** [comment]
No, it hasn't been fixed. ibus-1.4.1 with ibus-fep-1.4.3 and ibus-skk-1.4.0 (git master) has this issue, too.

**Comment by ueno** [comment]
It should be fixed with 8d9c8f0b20cd6dd246ddf2f31a24fd5399d548c9, though I guess it might be better to display the auxiliary text somewhere.

**Comment by tamo** [comment]
Agreed.
