### ISSUE TITLE
Sometimes unaware of preedit change?

### ISSUE THREAD

**Issue by tamo** [ueno/ibus-fep#8]
With ibus-skk,
"n N" doesn't display preedit status:

```
"n"     -> "n"
"n N"   -> "ん"    # gtk-immodule and "echo|skk" show "ん▽n"
"n N a" -> "ん▽な"
```

**Comment by ueno** [comment]
Thanks for the report.  It should be fixed with ueno/libskk@10706ee4914b135adf1d4172bb0165d98796deef.
